---
abstract: "Tom's Unicode Scripts So Life is Easier"
author:
  - 'Tom Christiansen <tchrist@perl.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 6.64
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.86, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Unicode-Tussle
no_index:
  directory:
    - t
    - inc
requires:
  Lingua::EN::Syllable: 0
  Lingua::JA::Romanize::Japanese: 0
  Lingua::KO::Hangul::Util: 0
  Lingua::KO::Romanize::Hangul: 0
  Lingua::ZH::Romanize::Pinyin: 0
  Unicode::GCString: 0
  Unicode::Unihan: 0
resources:
  repository: https://github.com/briandfoy/Unicode-Tussle.git
version: 1.08
